import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "@/components/ui/toaster";
import { Cardo, Inter, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";

export const cardo = Cardo({
  variable: "--font-english",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const notoSerifBangla = Noto_Serif_Bengali({
  variable: "--font-sans-bengali",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Qazi Akash | Writer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth focus:scroll-auto">
      <body
        className={`${cardo.variable} ${inter.variable} ${notoSerifBangla.variable} max-w-screen-2xl mx-auto scroll-smooth hover:scroll-auto`}
      >
        <div className="flex flex-col overflow-x-clip">
          <Navbar />
          <main className="flex flex-grow flex-col">{children}</main>
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
