import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "@/components/ui/toaster";
import { Cardo, Inter, Tiro_Bangla } from "next/font/google";
import "./globals.css";

export const cardo = Cardo({
  variable: "--font-english",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const tiroBangla = Tiro_Bangla({
  variable: "--font-tiro-bangla",
  weight: "400",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Qazi Akash | Writer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cardo.variable} ${inter.variable} ${tiroBangla.variable} max-w-screen-2xl mx-auto`}
      >
        <nav>
          <Navbar />
        </nav>
        <main>{children}</main>
        <section>
          <Footer />
        </section>
        <Toaster />
      </body>
    </html>
  );
}
