import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import { Roboto_Condensed, Tiro_Bangla } from "next/font/google";
import "./globals.css";

export const inter = Roboto_Condensed({
  variable: "--font-english",
  subsets: ["latin"],
  display: "swap",
});

export const tiroBangla = Tiro_Bangla({
  variable: "--font-tiro-bangla",
  weight: "400",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Qazi Akash | Writer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${tiroBangla.variable} bg-blue-100/50`}
      >
        <nav>
          <Navbar />
        </nav>
        <main>{children}</main>
        <section>
          <Footer />
        </section>
      </body>
    </html>
  );
}
